version: '3'
services:
    api:
        build:
            context: "./api"
            dockerfile: Dockerfile.api
        container_name: api-weather
        ports:
        - "5000:5000"
    prod:
        build:
            context: .
            dockerfile: Dockerfile.prod
        container_name: prodution-container
        environment:
            - REACT_APP_API_KEY=9c11e8478fb792bc6fe3b0d1d2ca96a7
        ports:
        - "8080:80"
