version: '3'
services:
    api:
        build:
            context: "./api"
            dockerfile: Dockerfile.api
        container_name: api-weather
        ports:
        - "5000:5000"
    prod:
        build:
            context: .
            dockerfile: Dockerfile.prod
        container_name: prodution-container
        ports:
        - "8080:80"
